---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    project: swiggy
    env: dev
spec:
  containers:
    - name: cont-1
      image: nginx
      ports:
        - containerPort: 80