---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: cont1
          image: ngnix
          ports:
            - containerPort: 80