 volumes(hostPath) deployment file
---
apiVersion: apps/v1
kind: Deploymnet
metadata:
  name: flm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont1
          image: nginx
          command: ["/bin/bash", "-c", "while true; do echo welcome; sleep 5; done"]
          volumeMounts:
            - name: myapp
              mountPath: "/opt/jenkins"

        - name: cont1
          image: nginx
          command: ["/bin/bash", "-c", "while true; do echo welcome; sleep 5; done"]
          volumeMounts:
             - name: myapp
              mountPath: "/etc/docker"
      volumes:
        - name: myapp
          hostPath:
            path: "/tmp/kubedata"